### ISSUE TITLE
Support for iOS 9.X

### ISSUE THREAD

**Issue by mad102190** [wibosco/GhostTypewriter#2]
Is there a specific reason this only supports iOS 10+? Would like to test it for use in our production app but we need to support iOS 9.X for the time being.

**Comment by wibosco** [comment]
hey, at the moment the project uses some apis that are only available on iOS 10 such as `scheduledTimer(withTimeInterval interval: TimeInterval, repeats: Bool, block: @escaping (Timer) -> Swift.Void) -> Timer` on the `Timer` class. But I'm sure this can be adapted to use those available in iOS 9.

I'd be open to reviewing a PR with this functionality if you fancied creating one?
