### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=50, address=0x1097021ad)

### ISSUE THREAD

**Issue by AnirudhWT** [wibosco/GhostTypewriter#21]
Hi Everyone,
I am trying to build a react native application by clicking on Play button on the top left corner of the Xcode.
Application gets launched in the simulator cream coloured screen comes up with the application name and written powered by react-native at the bottom after 1 minute cream coloured screen disappears i thin it is crashing.
Please help Thank you in advance.

**Comment by wibosco** [comment]
@AnirudhWT are you attempting to integrate GhostTypewriter into this react native app? Is it a project that you could link to?
