### ISSUE TITLE
Feature Request: Allow tapping to stop animation and show entire label

### ISSUE THREAD

**Issue by JStrawn** [wibosco/GhostTypewriter#9]
You know how in video games you can tap to just view the entire dialog label? This would be a neat feature. Love the library!

**Comment by JStrawn** [comment]
Actually just found a good workaround:

      titleLabel.stopTypewritingAnimation()
      titleLabel.typingTimeInterval = 0.0
      titleLabel.startTypewritingAnimation()

**Comment by wibosco** [comment]
@JStrawnmay this would actually make a really helpful convenience method, if you fancied adding it in and creating a PR?

**Comment by wibosco** [comment]
With version [2.0.0](https://github.com/wibosco/GhostTypewriter/releases/tag/2.0.0), GhostTypewriter now has a complete method -  `completeTypewritingAnimation()` - that will cause the reminder of the label's content to instantly appear.
